# Generated by Django 2.0.2 on 2018-02-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_text', models.CharField(max_length=250)),
                ('translation_text', models.CharField(max_length=250)),
                ('example_audio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PerformancePerExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('easiness_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_interval', models.PositiveSmallIntegerField()),
                ('date_last_studied', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruskeyverbs.Example')),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=30)),
                ('trans_infinitive', models.CharField(max_length=35, verbose_name='transliterated inifinitve')),
                ('aspect', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=200)),
                ('first_sg', models.CharField(max_length=30, verbose_name='first person singular')),
                ('second_sg', models.CharField(max_length=30, verbose_name='second person singular')),
                ('third_sg', models.CharField(max_length=30, verbose_name='third person singular')),
                ('first_pl', models.CharField(max_length=30, verbose_name='first person plural')),
                ('second_pl', models.CharField(max_length=30, verbose_name='second person plural')),
                ('third_pl', models.CharField(max_length=30, verbose_name='third person plural')),
                ('imperative_sg', models.CharField(max_length=30, verbose_name='imperative singular')),
                ('imperative_pl', models.CharField(max_length=30, verbose_name='imperative plural')),
                ('past_masc', models.CharField(max_length=30, verbose_name='masculine past')),
                ('past_fem', models.CharField(max_length=30, verbose_name='feminine past')),
                ('past_neut', models.CharField(max_length=30, verbose_name='neuter past')),
                ('past_pl', models.CharField(max_length=30, verbose_name='plural past')),
                ('audio_file', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruskeyverbs.Verb'),
        ),
    ]
