# Generated by Django 2.0.2 on 2018-04-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruskeyverbs', '0005_userstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='verb',
        ),
        migrations.DeleteModel(
            name='UserState',
        ),
    ]
